version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: vscode
    cap_add:
      - SYS_PTRACE
    shm_size: 2GB
    volumes:
      - type: volume
        source: python-packages
        target: $PWD/.venv
    command: sleep infinity

volumes:
  python-packages:
